config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#top'

  get    '/login', to: 'sessions#new'
  post   '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  resources :users do
    member do
      get 'edit_basic_info'
      patch 'update_basic_info'
      get 'attendances/edit_one_month'
      patch 'attendances/update_one_month'
    end
    resources :attendances, only: :update
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :attendances, dependent: :destroy
  attr_accessor :remember_token
  has_secure_password
  
  validates :name, presence: true, length: { maximum: 50 }
  
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 100 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: true
  
  validates :department, length: { in: 2..10 }, allow_blank: true
  validates :password, presence: true, length: { minimum: 6 }, allow_nil: true
  validates :basic_time, presence: true
  validates :work_time, presence: true
  
  # ランダムなトークンを返す
  def User.new_token
    SecureRandom.urlsafe_base64
  end
  
  # トークンをダイジェストに変換する
  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST : BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end

  # ハッシュ化したトークンをDBに保存する
  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end
  
  # remember_digestをnilにする
  def forget
    update_attribute(:remember_digest, nil)
  end

  # トークンがダイジェストと一致すればtrueを返します。
  def authenticated?(remember_token)
    return false if remember_digest.nil?
    BCrypt::Password.new(remember_digest).is_password?(remember_token)
  end
  
  # 検索機能
  def self.search(search)
    if search
      where(['name LIKE ?', "%#{search}%"])
    else
      none
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [
                                  :edit, :show, :update, :destroy,
                                  :edit_basic_info, :update_basic_info
                                 ]
  before_action :logged_in_user, only: [
                                        :index, :edit, :show, :update,
                                        :edit_basic_info, :update_basic_info
                                       ]
  before_action :correct_user, only: [:edit, :update]
  before_action :admin_user, only: [:index, :destroy, :edit_basic_info, :update_basic_info]
  before_action :admin_or_correct_user, only: :show
  before_action :set_one_month, only: :show
  
  def index
    @users = User.paginate(page: params[:page], per_page: 15)
    @search_users = User.all.page(params[:page]).search(params[:search])
    if params[:search] && @search_users.count == 0
      flash.now[:info] = "検索ワード「#{params[:search]}」に一致するユーザーは存在しません。"
    elsif params[:search].nil?
      @search_users = User.none
    elsif params[:search].blank?
      @search_users = User.none
      flash.now[:info] = "検索ワードを入力してください。"
    end
  end
  
  def create
    @user = User.new(user_params)
    if @user.save
      log_in @user
      flash[:success] = "新規登録に成功しました。"
      redirect_to user_path @user
    else
      render :new
    end
  end
  
  def new
    @user = User.new
  end
  
  def edit
  end
  
  def show
    @worked_sum = @attendances.where.not(started_at: nil).count
  end

  def update
    if @user.update_attributes(user_params)
      flash[:success] = "ユーザー情報を更新しました。"
      redirect_to edit_user_path
    else
      render :edit
    end
  end
  
  def destroy
    @user.destroy
    flash[:success] = "#{@user.name}のデータを削除しました。"
    redirect_to users_path
  end
  
  def edit_basic_info
  end
  
  def update_basic_info
    if params[:user][:all_user] == "1"
      users = User.all
      users.each do |user|
        user.update_attributes(basic_info_params)
      end
      flash[:success] = "全ユーザーの基本情報を更新しました。"
      redirect_to edit_basic_info_user_path
    else
      if @user.update_attributes(basic_info_params)
        flash[:success] = "基本情報を更新しました。"
        redirect_to edit_basic_info_user_path
      else
        render :edit_basic_info
      end
    end
  end
  
  private
    def user_params
      params.require(:user).permit(:name, :email, :department, :password, :password_confirmation)
    end
    
    def basic_info_params
      params.require(:user).permit(:work_time, :basic_time)
    end
end

app/helpers/users_helper.rb
module UsersHelper
  
  # 勤怠基本情報を指定のフォーマットで返します。
  def format_basic_info(time)
    format("%.2f", ((time.hour * 60) + time.min) / 60.0)
  end
end

app/views/users/_form.html.erb
<%= form_with(model: @user, local: true) do |f| %>
  <%= render 'shared/error_messages', object: @user %>

  <%= f.label :name, class: "label-#{yield(:class_text)}" %>
  <%= f.text_field :name, class: "form-control" %>

  <%= f.label :email, class: "label-#{yield(:class_text)}" %>
  <%= f.email_field :email, class: "form-control" %>

  <%= f.label :department, class: "label-#{yield(:class_text)}" %>
  <%= f.text_field :department, class: "form-control" %>

  <%= f.label :password, class: "label-#{yield(:class_text)}" %>
  <%= f.password_field :password, class: "form-control" %>

  <%= f.label :password_confirmation, class: "label-#{yield(:class_text)}" %>
  <%= f.password_field :password_confirmation, class: "form-control" %>

  <%= f.submit yield(:button_text), class: "btn btn-primary btn-block btn-#{yield(:class_text)}" %>

<% end %>

app/views/users/edit.html.erb
<% provide(:title, "Edit") %>
<% provide(:class_text, 'user-edit') %>
<% provide(:button_text, '更新') %>
<h1 class="headline">アカウント情報の更新</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render 'form' %>
  </div>
</div>

app/views/users/edit_basic_info.html.erb
<% provide(:title, "Edit basic-info") %>
<h1 class="headline">基本情報の更新</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_with(model: @user, url: update_basic_info_user_path(@user), local: true) do |f| %>
      <%= render 'shared/error_messages', object: @user %>

      <%= f.label :work_time, "指定勤務時間", class: "label-basic-info" %>
      <%= f.time_field :work_time, class: 'form-control' %>

      <%= f.label :basic_time, "基本勤務時間", class: "label-basic-info" %>
      <%= f.time_field :basic_time, class: 'form-control' %>
      
      <%= f.label :all_user, class: "checkbox inline checkbox-basic-time", for: "all_user" do %>
        <%= f.check_box :all_user %>
        <span>全ユーザを編集対象にする。</span>
      <% end %>
      
      <%= f.submit "編集", class: "btn btn-primary btn-block btn-basic-info" %>
    <% end %>
  </div>
</div>

app/views/users/index.html.erb
<% provide(:title, 'Users') %>

<% if @search_users.count >= 1 %>
　<% provide(:headline_text, '検索結果') %>
<% else %>
  <% provide(:headline_text, '全てのユーザー') %>
<% end %>

<h1 class="headline"><%= "#{yield(:headline_text)}" %></h1>

<div class="pull-right">
  <%= form_tag(users_path, :method => "get") do %>
    <%= text_field_tag :search, params[:search] %>
    <%= submit_tag "Search", :name => nil %>
  <% end %>
</div>

<% if @search_users.count >= 1 %>
  <div class="row">
    <div class="col-md-10 col-md-offset-1">
      <table class="table table-hover" id="table-users">
        <thead>
          <tr>
            <th>名前</th>
          </tr>
        </thead>
        <tbody>
          <% @search_users.each do |user| %>
            <tr>
              <td>
                <%= link_to user.name, user_path(user.id) %>
                <% unless user.admin? %>
                  &nbsp;|&nbsp;
                  <%= link_to "基本情報編集", edit_basic_info_user_path(user.id) %>
                  &nbsp;|&nbsp;
                  <%= 
                    link_to "削除", user, method: :delete,
                    data: { confirm: "「#{user.name}」を削除してよろしいですか？" }
                  %>
                <% end %>
              </td>
              <td></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
<% else %>
  <div class="row">
    <div class="col-md-10 col-md-offset-1">
      <%= will_paginate %>
        <table class="table table-hover" id="table-users">
          <thead>
            <tr>
              <th>名前</th>
            </tr>
          </thead>
          <tbody>
            <% @users.each do |user| %>
              <tr>
                <td>
                  <%= link_to user.name, user_path(user.id) %>
                  <% unless user.admin? %>
                    &nbsp;|&nbsp;
                    <%= link_to "基本情報編集", edit_basic_info_user_path(user.id) %>
                    &nbsp;|&nbsp;
                    <%= 
                      link_to "削除", user, method: :delete,
                      data: { confirm: "「#{user.name}」を削除してよろしいですか？" }
                    %>
                  <% end %>
                </td>
                <td></td>
              </tr>
            <% end %>
          </tbody>
        </table>
      <%= will_paginate %>
    </div>
  </div>
<% end %>

app/views/users/new.html.erb
<% provide(:title, "SignUp") %>
<% provide(:class_text, 'signup') %>
<% provide(:button_text, '作成') %>
<h1 class="headline">アカウント作成</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render 'form' %>
  </div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>

<table class="table table-bordered table-condensed table-border-duplication">
  <div class="row">
    <tr>
      <th class="col-md-4 table-head">
        <div>
        <%= link_to "◀", user_path(date: @first_day.prev_month), class: "btn btn-primary" %>
        &nbsp;
        <%= l(@first_day, format: :middle) %>
        &nbsp;
        時間管理表
        &nbsp;
        <%= link_to "▶", user_path(date: @first_day.next_month), class: "btn btn-primary" %>
        </div>
      </th>
      <th class="col-md-2 table-head">指定勤務時間&emsp;<%= format_basic_info(@user.work_time) %></th>
      <th class="col-md-4 table-head"><%= format_basic_info(@user.basic_time) %>&emsp;基本時間</th>
      <th class="col-md-2 table-head">初日&emsp;<%= l(@first_day, format: :short_zero) %></th>
    </tr>
  </div>
</table>

<table class="table table-bordered table-condensed center">
  <div class="row">
    <tr>
      <th class="col-md-4 table-head">所属&emsp;<%= @user.department.present? ? @user.department : "未所属" %></th>
      <th class="col-md-2 table-head">氏名&emsp;<%= @user.name %></th>
      <th class="col-md-1 table-head">コード</th>
      <th class="col-md-1 table-head"><%= @user.id %></th>
      <th class="col-md-2 table-head">出勤日数&emsp;<%= @worked_sum %>日</th>
      <th class="col-md-2 table-head">締め&emsp;<%= l(@last_day, format: :short_zero) %></th>
    </tr>
  </div>
</table>

<%= 
  link_to "勤怠を編集", attendances_edit_one_month_user_path(date: @first_day),
  class: "btn btn-primary btn-attendance-edit"
%>

<table class="table table-bordered table-condensed center table-striped">
  <thead>
    <tr>
      <th rowspan="2" class="table-head">日付</th>
      <th rowspan="2" class="table-head">曜日</th>
      <th colspan="3" class="table-head">出社</th>
      <th colspan="3" class="table-head">退社</th>
      <th rowspan="2" class="table-head">在社時間</th>
      <th rowspan="2" class="table-head">備考</th>
    </tr>
    <tr>
      <th class="table-head">時</th>
      <th class="table-head">分</th>
      <th class="table-head"></th>
      <th class="table-head">時</th>
      <th class="table-head">分</th>
      <th class="table-head"></th>
    </tr>
    <tr>
  </thead>
  <tbody>
    <% @attendances.each do |day| %>
    <tr>
      <td class="table-data"><%= l(day.worked_on, format: :short) %></td>
      <td class='table-data <%= "wday#{day.worked_on.wday}" %>'>
        <%= $days_of_the_week[day.worked_on.wday] %>
      </td>
      <td class="table-data"><%= day.started_at.hour if day.started_at.present? %></td>
      <td class="table-data">
        <%= fifteen_minutes_conversion(day.started_at.min) if day.started_at.present? %>
      </td>
      <td class="table-data">
      <% if btn_text = attendance_state(day) %>
        <%=
          link_to "#{btn_text}", user_attendance_path(@user, day),
          method: :patch, class: "btn btn-primary btn-attendance"
        %>
      <% end %>
      </td>
      <td class="table-data"><%= day.finished_at.hour if day.finished_at.present? %></td>
      <td class="table-data">
        <%= fifteen_minutes_conversion(day.finished_at.min) if day.finished_at.present? %>
      </td>
      <td></td>
      <td class="table-data">
      <% if day.started_at.present? && day.finished_at.present? %>
        <%= str_times = working_times(day.started_at, day.finished_at) %>
        <% @total_working_times = @total_working_times.to_f + str_times.to_f %>
      <% end %>
      </td>
      <td class="table-data"><%= day.note %></td>
    </tr>
    <% end %>
  </tbody>
  <tfoot class="table-foot">
    <td colspan="2"><%= total_bacic_times(@user.basic_time) %></td>
    <td colspan="6"></td>
    <td><%= format("%.2f", @total_working_times.to_f) %></td>
    <td></td>
  </tfoot>
</table>