config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#top'

  get    '/login', to: 'sessions#new'
  post   '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  resources :users do
    member do
      get 'edit_basic_info'
      patch 'update_basic_info'
      get 'attendances/edit_one_month'
      patch 'attendances/update_one_month'
    end
    resources :attendances, only: :update
  end
end

app/models/attendance.rb
class Attendance < ApplicationRecord
  belongs_to :user
  
  validates :worked_on, presence: true
  validates :note, length: { maximum: 50 }
  validates :started_at, absence: true, on: :started_only_edit

  validate :finished_at_is_invalid_without_a_started_at
  validate :started_at_than_finished_at_fast_if_invalid
  
  # 出勤時間が存在しない場合に、退勤時間を無効にする
  def finished_at_is_invalid_without_a_started_at
    errors.add(:started_at, "が必要です") if started_at.blank? && finished_at.present?
  end
  
  # 出勤・退勤時間がどちらも存在する時、出勤時間より早い退勤時間を無効にする
  def started_at_than_finished_at_fast_if_invalid
    if started_at.present? && finished_at.present?
      errors.add(:started_at, "より早い退勤時間は無効です") if started_at > finished_at
    end
  end
end

app/controllers/attendances_controller.rb
class AttendancesController < ApplicationController
  before_action :set_user, only: [:edit_one_month, :update_one_month]
  before_action :set_one_month, only: :edit_one_month
  before_action :logged_in_user, only: [:update, :edit_one_month]
  before_action :admin_or_correct_user, only: [:update, :edit_one_month, :update_one_month]
  
  UPDATE_ERROR_MSG = "勤怠登録に失敗しました。やり直してください。"

  def update
    @user = User.find(params[:user_id])
    @attendance = Attendance.find(params[:id])
    if @attendance.started_at.nil?
      if @attendance.update_attributes(started_at: Time.current.change(sec: 0))
        flash[:info] = "おはようございます！"
      else
        flash[:danger] = UPDATE_ERROR_MSG
      end
    elsif @attendance.finished_at.nil?
      if @attendance.update_attributes(finished_at: Time.current.change(sec: 0))
        flash[:info] = "お疲れ様でした。"
      else
        flash[:danger] = UPDATE_ERROR_MSG
      end
    end
    redirect_to @user
  end
  
  def edit_one_month
  end
  
  def update_one_month
    ActiveRecord::Base.transaction do
      @user = User.find(params[:id])
      attendances_params.each do |id, item|
        user_attendance = @user.attendances.find(id)
        item_started_at = item[:started_at]
        item_finished_at = item[:finished_at]
        attendance = Attendance.find(id)
        if user_attendance.started_at.blank? && !item_started_at.blank?
          if item_finished_at.blank?
            attendance.started_at = item_started_at
            attendance.save!(context: :started_only_edit)
          end
        end
        attendance.update_attributes!(item)
        
        # 元のコード
        # attendance = Attendance.find(id)
        # attendance.update_attributes!(item)
      end
    end
    flash[:success] = "1ヵ月分の勤怠情報を更新しました。"
    redirect_to user_url(date: params[:date])
  rescue ActiveRecord::RecordInvalid
    flash[:danger] = "無効な入力データがあった為、更新をキャンセルしました。"
    redirect_to attendances_edit_one_month_user_url(date: params[:date])
  end
  
  private
    # 1ヶ月分の勤怠情報を扱う。
    def attendances_params
      params.require(:user).permit(attendances: [:started_at, :finished_at, :note])[:attendances]
    end
end

app/helpers/attendances_helper.rb
module AttendancesHelper
    
  # 出社・退社ボタンの表示/非表示の判定材料を返す。
  def attendance_state(attendance)
    if Date.current == attendance.worked_on
      return '出社' if attendance.started_at.nil?
      return '退社' if attendance.started_at.present? && attendance.finished_at.nil?
    end
    false
  end
  
  # 出社時間と退社時間を受け取り、在社時間を計算して返す。
  # def working_times(start, finish)
  #   format("%.2f", (((finish - start) / 60) / 60.0))
  # end
  
  # 在社時間を計算して返す。15分単位ver
  def working_times(start, finish)
    start_time = start.hour * 60 + fifteen_minutes_conversion(start.min)
    finish_time = finish.hour * 60 + fifteen_minutes_conversion(finish.min)
    format("%.2f", (finish_time - start_time) / 60.0)
  end
  
  # 総合勤務時間を返す。
  def total_bacic_times(time)
    format("%.2f", (((time.hour * 60) + time.min) * @worked_sum) / 60.0)
  end
  
  # 勤怠表示画面の時刻表示（分）を15分単位にする。
  def fifteen_minutes_conversion(time)
    if time <= 14
      0
    elsif time <= 29
      15
    elsif time <= 44
      30
    else
      45
    end
  end
end

app/views/attendances/edit_one_month.html.erb
<% provide(:title, @user.name) %>
<h1 class="headline headline-one">勤怠編集画面</h1>

<%= 
  form_with(model: @user, url: attendances_update_one_month_user_path(date: @first_day),
  local: true, method: :patch) do |f|
%>
  <table class="table table-bordered table-condensed center table-striped">
    <thead>
      <div class="row">
        <tr>
          <th class="col-md-1 table-head">日付</th>
          <th class="col-md-1 table-head">曜日</th>
          <th class="col-md-2 table-head">出社</th>
          <th class="col-md-2 table-head">退社</th>
          <th class="col-md-1 table-head">在社時間</th>
          <th class="col-md-2 table-head">備考</th>
          <th class="col-md-1 table-head">残業指示</th>
          <th class="col-md-1 table-head">指示者</th>
        </tr>
      </div>
    </thead>
    <tbody>
      <% @attendances.each do |day| %>
        <%= f.fields_for "attendances[]", day do |attendance| %>
          <tr>
            <td class="table-data"><%= l(day.worked_on, format: :short) %></td>
            <td class='table-data <%= "wday#{day.worked_on.wday}" %>'>
              <%= $days_of_the_week[day.worked_on.wday] %>
            </td>
            <% if day.worked_on > Date.current %>
              <td>
                <%= attendance.time_field :started_at, readonly: true, class: "form-control" %>
              </td>
              <td>
                <%= attendance.time_field :finished_at, readonly: true, class: "form-control" %>
              </td>
            <% else %>
              <td><%= attendance.time_field :started_at, class: "form-control" %></td>
              <td><%= attendance.time_field :finished_at, class: "form-control" %></td>
            <% end %>
            <td class="table-data">
              <% if day.started_at.present? && day.finished_at.present? %>
                <%= working_times(day.started_at, day.finished_at) %>
              <% end %>
            </td>
            <td><%= attendance.text_field :note, class: "form-control" %></td>
            <td></td>
            <td></td>
          </tr>
        <% end %>
      <% end %>
    </tbody>
  </table>
  
  <div class="center">
    <%= link_to "キャンセル", user_path(date: @first_day), class: "btn btn-primary btn-lg" %>
    <%= f.submit "編集を保存する", class: "btn btn-lg btn-primary" %>
  </div>
<% end %>