config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#top'

  get    '/login', to: 'sessions#new'
  post   '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  resources :users do
    member do
      get 'edit_basic_info'
      patch 'update_basic_info'
      get 'attendances/edit_one_month'
      patch 'attendances/update_one_month'
    end
    resources :attendances, only: :update
  end
end

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <div class="row">
      <% if logged_in? %>
        <% provide(:link_text, user_path(current_user)) %>
      <% else %>
        <% provide(:link_text, root_path) %>
      <% end %>
      <%= link_to "勤怠システム", "#{yield(:link_text)}", class:"logo" %>
      <nav>
        <ul class="nav navbar-nav navbar-right">
          <li><%= link_to "トップへ", "#{yield(:link_text)}" %></li>
          <% unless logged_in? %>
            <li><%= link_to "ログイン", login_path %></li>
          <% end %>
          <% if logged_in? && current_user.admin? %>
            <li><%= link_to "ユーザ一覧", users_path %></li>
            <li><%= link_to "基本情報の修正", edit_basic_info_user_path(current_user) %></li>
          <% end %>
          <% if logged_in? %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              アカウント <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "アカウント情報の更新", edit_user_path(current_user)%></li>
              <li><%= link_to "ログアウト", logout_path, method: :delete %></li>
            </ul>
          </li>
          <% end %>  
        </ul>
      </nav>
    </div>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all',
                               'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application',
                               'data-turbolinks-track': 'reload' %>
    <%= render 'layouts/shim' %>
  </head>

  <body class="body-common">
    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |message_type, msg| %>
        <div class="alert alert-<%= message_type %>"><%= msg %></div>
      <% end %>
      <%= yield %>
      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>